image:
  - Visual Studio 2017

platform:
  - x64

environment:
  global:
    GAMEKIT_SYSTEM_NAME: mds
    GAMEKIT_APPLICATION_PACKAGE: mds
    GAMEKIT_APPLICATION_MAIN_CLASS: example
    GAMEKIT_ARTIFACT: $(GAMEKIT_SYSTEM_NAME)-x86-64-windows-$(APPVEYOR_REPO_TAG_NAME).zip
    GAMEKIT_BUILD_DIR: $(TMP)\$(GAMEKIT_SYSTEM_NAME)

skip_non_tags: true

branches:
  only:
    - master
    - "/^v\\d+(\\.\\d+)+$/"

install:
  - set PATH=C:\msys64\usr\bin\;%PATH%
  - pacman --noconfirm -S zip
  - sh -c "curl -L http://bodge.borodust.org/files/install.sh | sh -s ccl"

build_script:
  - >
    sh -c "$HOME/bin/lisp $HOME/bodge/scripts/build-gamekit-system.lisp
    %GAMEKIT_SYSTEM_NAME% %GAMEKIT_APPLICATION_PACKAGE% %GAMEKIT_APPLICATION_MAIN_CLASS%
    $(cygpath -u '%APPVEYOR_BUILD_FOLDER%')
    $(cygpath -u '%GAMEKIT_BUILD_DIR%')"
  - mv %GAMEKIT_BUILD_DIR%\%GAMEKIT_SYSTEM_NAME%.zip %GAMEKIT_ARTIFACT%

artifacts:
  - path: "%GAMEKIT_ARTIFACT%"
    name: release_archive

deploy:
  provider: GitHub
  release: $(APPVEYOR_REPO_TAG_NAME)
  tag: $(APPVEYOR_REPO_TAG_NAME)
  description: $(APPVEYOR_REPO_COMMIT_MESSAGE)
  auth_token:
     secure: 9tVgRQoTKB1I76ZeCiYGavkHAbC3+C14QCGzf7CB3ItGSgtUT3rq1sBcL3YzH6/2
  artifact: release_archive
  force_update: true
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true
